test: add unit test
jina-ai/executor-qdrant-indexer pull request #1
Opened 2022-04-28 13:29 UTC by azayz

2022-04-29 13:55 UTC, numb3r3 requested changes
Please remember to offer the instructions about how to start qdrant in the README. You can borrow some ideas from https://github.com/jina-ai/executor-hnsw-postgres

2022-05-09 13:53 UTC, JoanFM requested changes

2022-05-09 13:53 UTC, JoanFM commented on executor.py
> +        n_dim: Optional[int] = 128,
Are all these parameters really Optional?

2022-05-11 15:14 UTC, JoanFM approved these changes

2022-05-11 15:16 UTC, merged